# Generated by Django 3.2.5 on 2021-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='high_weight',
            field=models.IntegerField(default=False, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='low_weight',
            field=models.IntegerField(default=False, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='medium_weight',
            field=models.IntegerField(default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='weight',
            field=models.IntegerField(default=False, max_length=3),
        ),
    ]
