# Generated by Django 3.2.5 on 2021-07-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210708_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='high_weight',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='low_weight',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='medium_weight',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='weight',
            field=models.IntegerField(default=False),
        ),
    ]
