# Generated by Django 3.2.5 on 2021-07-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210708_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='account',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='account',
            field=models.ManyToManyField(to='api.Account'),
        ),
    ]
