# Generated by Django 3.2.5 on 2021-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210721_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ManyToManyField(to='api.AccountUser'),
        ),
    ]
