# Generated by Django 3.2.5 on 2021-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_user_transaction_signers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejecters',
            field=models.ManyToManyField(related_name='rejected_transactions', to='api.AccountUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='available_to_sign',
            field=models.BooleanField(default=True),
        ),
    ]
