# Generated by Django 3.2.5 on 2021-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='requestee_username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
